In [13]:
import sys
sys.path.append('..')
from src.order_book import OrderBook, Side
from src.market_maker import MarketMaker
from src.simulator import Simulator

import requests
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

print("Libraries loaded successfully")

Libraries loaded successfully

In [14]:
def get_btc_trades(limit=1000):
    url = "https://api.exchange.coinbase.com/products/BTC-USD/trades"
    params = {"limit": limit}
    response = requests.get(url, params=params)
    data = response.json()
    df = pd.DataFrame(data)
    return df

trades = get_btc_trades()
print(f"Got {len(trades)} trades")

trades['price'] = pd.to_numeric(trades['price'])
trades['size'] = pd.to_numeric(trades['size'])
trades['time'] = pd.to_datetime(trades['time'])

trades = trades.sort_values('time').reset_index(drop=True)
trades = trades.set_index("time")


print(trades.dtypes)
trades.head()

Got 1000 trades
trade_id      int64
side         object
size        float64
price       float64
dtype: object

                                    trade_id  side      size     price
time
2026-05-18 16:24:45.811606+00:00  1020560996  sell  0.003880  76424.51
2026-05-18 16:24:45.811606+00:00  1020561013  sell  0.000015  76438.56
2026-05-18 16:24:45.811606+00:00  1020561012  sell  0.104988  76437.72
2026-05-18 16:24:45.811606+00:00  1020561011  sell  0.001308  76436.43
2026-05-18 16:24:45.811606+00:00  1020561010  sell  0.015520  76436.25

In [15]:
book = OrderBook()
mm = MarketMaker(starting_wealth=100000, order_book=book)
sim = Simulator(mm=mm, book=book, df=trades, window=20)

mm.start_session()
sim.run()

In [16]:
results = sim.get_results()
results.tail(10)

,Mid_Price,Reservation_Price,Bid,Ask,Position,PnL,Spread
Time,,,,,,,
990,76297.2385,76297.104943,76296.259559,76297.950327,0.333894,99997.556325,1.690768
991,76296.6955,76296.557943,76295.712559,76297.403327,0.343894,99998.294125,1.690768
992,76296.2530,76296.115443,76295.270059,76296.960827,0.343894,99998.294125,1.690768
993,76295.8100,76295.672443,76294.827059,76296.517827,0.343894,99998.294125,1.690768
994,76295.3490,76295.210523,76294.365139,76296.055907,0.346194,99998.462075,1.690768
995,76294.8925,76294.754023,76293.908639,76295.599407,0.346194,99998.462075,1.690768
996,76294.7085,76294.570023,76293.724639,76295.415407,0.346194,99998.462075,1.690768
997,76294.7930,76294.654523,76293.809139,76295.499907,0.346194,99998.462075,1.690768
998,76294.8050,76294.666424,76293.821040,76295.511808,0.346442,99998.395644,1.690768
999,76294.7805,76294.641924,76293.796540,76295.487308,0.346442,99998.395644,1.690768